<a href="https://colab.research.google.com/github/enslern/The-AI-engineer-course-2026-Complete-AI-bootcamp/blob/main/text_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report

In [4]:
data=pd.DataFrame([("i love spending time with my friends and family", "positive"),
                     ("that was the best meal i've ever had in my life", "positive"),
                     ("i feel so grateful for everything i have in my life", "positive"),
                     ("i received a promotion at work and i couldn't be happier", "positive"),
                     ("watching a beautiful sunset always fills me with joy", "positive"),
                     ("my partner surprised me with a thoughtful gift and it made my day", "positive"),
                     ("i am so proud of my daughter for graduating with honors", "positive"),
                     ("listening to my favorite music always puts me in a good mood", "positive"),
                     ("i love the feeling of accomplishment after completing a challenging task", "positive"),
                     ("i am excited to go on vacation next week", "positive"),
                     ("i feel so overwhelmed with work and responsibilities", "negative"),
                     ("the traffic during my commute is always so frustrating", "negative"),
                     ("i received a parking ticket and it ruined my day", "negative"),
                     ("i got into an argument with my partner and we're not speaking", "negative"),
                     ("i have a headache and i feel terrible", "negative"),
                     ("i received a rejection letter for the job i really wanted", "negative"),
                     ("my car broke down and it's going to be expensive to fix", "negative"),
                     ("i'm feeling sad because i miss my friends who live far away", "negative"),
                     ("i'm frustrated because i can't seem to make progress on my project", "negative"),
                     ("i'm disappointed because my team lost the game", "negative")
                    ],
                    columns=['text', 'sentiment'])

In [5]:
data=data.sample(frac=1).reset_index(drop=True)

In [6]:
data.head()

                                                text sentiment
0  my partner surprised me with a thoughtful gift...  positive
1  i received a promotion at work and i couldn't ...  positive
2              i have a headache and i feel terrible  negative
3  i'm feeling sad because i miss my friends who ...  negative
4  i'm frustrated because i can't seem to make pr...  negative

In [7]:
x=data["text"]
y=data["sentiment"]

In [13]:
countvec=CountVectorizer()
countfit=countvec.fit_transform(x)
bag_of_words=pd.DataFrame(countfit.toarray(),columns=countvec.get_feature_names_out())
bag_of_words.head()

,accomplishment,after,always,am,an,and,argument,at,away,be,...,vacation,ve,wanted,was,watching,we,week,who,with,work
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
x_train,x_test,y_train,y_test=train_test_split(bag_of_words,y,test_size=0.3,random_state=7)

LOGISTIC REGRESSION

In [15]:
lr=LogisticRegression(random_state=1).fit(x_train,y_train)

In [16]:
y_pred_lr=lr.predict(x_test)

In [25]:
accuracy_score(y_test,y_pred_lr)

0.6666666666666666

In [18]:
print(classification_report(y_pred_lr,y_test,zero_division=0))

              precision    recall  f1-score   support

    negative       1.00      0.60      0.75         5
    positive       0.33      1.00      0.50         1

    accuracy                           0.67         6
   macro avg       0.67      0.80      0.62         6
weighted avg       0.89      0.67      0.71         6

NAIVE BAYES

In [20]:
from sklearn.naive_bayes import MultinomialNB

In [23]:
nb=MultinomialNB().fit(x_train,y_train)

In [24]:
y_pred_nb=nb.predict(x_test)

In [26]:
accuracy_score(y_test,y_pred_nb)

0.6666666666666666

In [27]:
print(classification_report(y_test,y_pred_nb,zero_division=0))

              precision    recall  f1-score   support

    negative       0.60      1.00      0.75         3
    positive       1.00      0.33      0.50         3

    accuracy                           0.67         6
   macro avg       0.80      0.67      0.62         6
weighted avg       0.80      0.67      0.62         6

LINEAR SUPPORT VECTOR MACHINE (SVM)

In [28]:
from sklearn.linear_model import LogisticRegression , SGDClassifier

In [31]:
svm=SGDClassifier().fit(x_train,y_train)

In [34]:
y_pred_svm=svm.predict(x_test)

In [36]:
accuracy_score(y_test,y_pred_svm)

0.5

In [37]:
print(classification_report(y_test,y_pred_svm,zero_division=0))

              precision    recall  f1-score   support

    negative       0.50      0.67      0.57         3
    positive       0.50      0.33      0.40         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6